name: tappayflutterplugin
description: This is a Flutter plugin that help developer to use Tappay.
version: 0.0.49
homepage: https://github.com/TungWang/tappay_flutter_plugin
repository: https://github.com/TungWang/tappay_flutter_plugin

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tungwang.tappayflutterplugin
        pluginClass: TappayflutterpluginPlugin
      ios:
        pluginClass: TappayflutterpluginPlugin
